### ISSUE TITLE
Can this Distro have support boot from LiveISO? use iso-scan/filename=${iso_path}...

### ISSUE THREAD

**Issue by t829702** [MX-Linux/mx-iso-template#15]
I see the this repo has `iso-template/boot/grub/loopback.cfg` has this `iso-scan/filename=${iso_path}...` but somehow why not get into the LiveISO?

```grub
menuentry "Try Ubuntu without installing" {
	set gfxpayload=keep
	linux	/casper/vmlinuz.efi  file=/cdrom/preseed/ubuntu.seed boot=casper iso-scan/filename=${iso_path} quiet splash --
	initrd	/casper/initrd.lz
}
```

this template is still from Ubuntu, with Ubuntu what I usually do is to copy the ISO on to a subdirectory of a USB drive, for example if copied the iso at `/ubuntu/ubuntu-20.10.iso`, then make this entry into the USB drive's `/boot/grub/grub.cfg` it can boot up Ubuntu as Live mode,

```grub
menuentry "Try Ubuntu without installing" {
	set gfxpayload=keep
	set iso_path="/ubuntu/ubuntu-20.10.iso"
	loopback loop ${iso_path}
	linux	(loop)/casper/vmlinuz.efi  file=/cdrom/preseed/ubuntu.seed boot=casper iso-scan/filename=${iso_path} quiet splash --
	initrd	(loop)/casper/initrd.lz
}
```

But so far I downloaded the `MX-19.3.iso` I don't see it has support boot from LiveISO?

**Comment by dolphinoracle** [comment]
you can do what you want, but I don't know how myself.  I suggest you post in our forum rather than in the gitrepo where our resident grub gurus can help.

**Comment by dolphinoracle** [comment]
check out this post for a way to set up a boot from iso situation.

https://forum.mxlinux.org/viewtopic.php?p=486820#p486820

just change the name of the iso in the grub stanza to fit what you are using.
